trainer:
  target: trainer.TrainerDifIR

four_channel_autoencoder:
  ckpt_path: "checkpoints/sen2naip_vae_from_opensr.ckpt"
  trainable: false
  compile: false
  params:
    embed_dim: 4
    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 4
      out_ch: 4
 # --- CORRECTED ARCHITECTURE PARAMETERS ---
      ch: 128
      ch_mult: [ 1, 2, 4, 4 ] # This creates the larger 512-channel layers
      num_res_blocks: 2
      # ---
      attn_resolutions: [16] # updated
      dropout: 0.0

model:
  target: models.unet.DiTSRModel
  ckpt_path: ~
  params:
    image_size: 16
    in_channels: 8
    model_channels: 160
    out_channels: 4
    attention_resolutions: [64, 32, 16, 8]
    dropout: 0.1
    channel_mult: [1, 2, 2, 4]
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 32
    swin_depth: 6
    swin_embed_dim: 192
    window_size: 4
    mlp_ratio: 4
    cond_lq: True
    lq_size: 64
    # --- FIX: Explicitly tell the model our LR image has 4 channels ---
    lq_channels: 4

diffusion:
  target: models.script_util.create_gaussian_diffusion
  params:
    sf: 4
    schedule_name: exponential
    schedule_kwargs:
      power: 0.3
    etas_end: 0.99
    steps: 15
    min_noise_level: 0.04
    kappa: 2.0
    loss_type: L1
    #predict_type: xstart
    # --- FIX: Set the timestep respacing ---
    model_mean_type: START_X
    timestep_respacing: "ddim15"
    scale_factor: 1.0
    normalize_input: True
    latent_flag: True


degradation:
  sf: 4
  resize_prob: [0.2, 0.7, 0.1]
  resize_range: [0.15, 1.5]
  gaussian_noise_prob: 0.5
  noise_range: [1, 30]
  poisson_scale_range: [0.05, 3.0]
  gray_noise_prob: 0.4
  jpeg_range: [30, 95]
  second_order_prob: 0.5
  second_blur_prob: 0.8
  resize_prob2: [0.3, 0.4, 0.3]
  resize_range2: [0.3, 1.2]
  gaussian_noise_prob2: 0.5
  noise_range2: [1, 25]
  poisson_scale_range2: [0.05, 2.5]
  gray_noise_prob2: 0.4
  jpeg_range2: [30, 95]
  gt_size: 256
  resize_back: False
  use_sharp: False

data:
  train:
    name: SEN2NAIP_Train
    type: SEN2NAIPDataset
    # Point to the new train directory
    dataroot_gt: /Volumes/SSD/GIS/cross-sensor/train/
    dataroot_lq: ~ # No longer needed
    io_backend: {type: disk}

    gt_size: 256
    scale: 4
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    phase: train

  val:
    name: SEN2NAIP_Val
    type: SEN2NAIPDataset
    # Point to the new val directory
    dataroot_gt: /Volumes/SSD/GIS/cross-sensor/val/
    dataroot_lq: ~ # No longer needed
    io_backend: {type: disk}
    scale: 4
    phase: val
    gt_size: 256

train:
  lr: 0.00005
  lr_min: 0.00002
  lr_schedule: ~
  warmup_iterations: 5000
  batch: [64, 8]
  microbatch: 8
  num_workers: 4
  prefetch_factor: 2
  weight_decay: 0
  ema_rate: 0.999
  iterations: 300000
  save_freq: 10000
  log_freq: [200, 2000, 1]
  local_logging: True
  tf_logging: False
  use_ema_val: True
  val_freq: ${train.save_freq}
  val_y_channel: True
  val_resolution: ${model.params.lq_size}
  val_padding_mode: reflect
  use_amp: True
  seed: 123456
  global_seeding: False
  compile:
    flag: False
    mode: reduce-overhead